title: "Sources"
desc: "This is the list of sources that support the statements made on the AlgonquinDesign.ca web site."

ai:
  - title: "some_title"
    volume:
    issn:
    shorttitle:
    url:
    doi:
    abstract:
    language:
    number:
    urldate:
    journal:
    year:
    pages:
    file:
