title: "Sources"
desc: "This is the list of sources that support the statements made on the AlgonquinDesign.ca web site."
ai:
  - title: "some_title"
    volume:
    issn:
    shorttitle:
    url:
    doi:
    abstract:
    language:
    number:
    urldate:
    journal:
    year:
    pages:
    file:
skeptics: # this article /articles/need-for-numbers/
  - title: "An Investment of a Lifetime?"
    author: "Statistics Canada"
    url: "https://www150.statcan.gc.ca/n1/pub/11f0019m/11f0019m2014359-eng.htm"
  - title: "The Cumulative Earnings of Postsecondary Graduates Over 20 Years"
    author: "Statistics Canada"
    url: "https://www150.statcan.gc.ca/n1/pub/11-626-x/11-626-x2014040-eng.htm"
  - title: "CBC asks: Is university still worth it? We answered"
    author: "OCUFA"
    url: "https://ocufa.on.ca/cbc-asks-is-university-still-worth-it/"
  - title: "Still Worth It After All These Years"
    author: "HECQO"
    url: "https://heqco.ca/wp-content/uploads/2020/03/Still_Worth_It_EN.pdf"
  - title: "How Much Do They Make?"
    author: "Labour Market Information Council"
    url: "https://lmic-cimt.ca/how-much-do-they-make/"
  - title: "Mental Health Indicators..."
    author: "Public Health Ontario"
    url: "https://www.publichealthontario.ca/-/media/Documents/C/24/chscy-mental-health-indicators-data.pdf?rev=e60689ac60c047a09f59c3bb59070aba&sc_lang=en"
  - title: "Health Outcomes in Canadian Adolescents..."
    author: "National Library of Medicine"
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4330444/"
  - title: "The Effect of College Education on Health..."
    author: "CEDIA.ca"
    url: "https://creei.ca/wp-content/uploads/2019/08/cahier_18_13_college_education_health_mortality_canada.pdf"
  - title: "Civic Engagement"
    author: "Environmental Institute.org"
    url: "https://www.environicsinstitute.org/docs/default-source/project-documents/canadian-millennial-social-values-study/civic-engagement.pdf?sfvrsn=14e66c5_2"
  - title: "Study: Impact of education on civic engagement in rural and urban Canada"
    author: "Statistics Canada"
    url: "https://www150.statcan.gc.ca/n1/daily-quotidien/060717/dq060717c-eng.htm"
